import { useEffect, useState } from "react";
import Head from "next/head";
// import icon
import { BsClipboardPlus } from "react-icons/bs";

const addToClipboard = (text) => {
  navigator.clipboard.writeText(text);
};

const removeDuplicate = (data) => {
  const seen = new Set();

  const filteredArr = data.filter((el) => {
    const duplicate = seen.has(el.id);
    seen.add(el.id);
    return !duplicate;
  });
  return filteredArr;
};

export default function Home() {
  const [chatData, setChatData] = useState([]);
  useEffect(() => {
    fetch(
      "https://api.telegram.org/bot1544271466:AAEqU36QIKtTDYGtZtbCNQkawFVl7cptc1I/getUpdates"
    )
      .then((res) => res.json())
      .then((data) => {
        const chatData = data.result
          .map((res) => {
            if ("my_chat_member" in res) {
              return {
                id: res.my_chat_member.chat.id,
                title: res.my_chat_member.chat.title,
              };
            }
            if ("message" in res) {
              return {
                id: res.message.chat.id,
                title: res.message.chat.title,
              };
            }
          })
          .filter((item) => item != undefined);
        const filteredData = removeDuplicate(chatData);
        setChatData(filteredData);
      });
  }, []);

  return (
    <div>
      <Head>
        <title>Gym Data </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <style>{`
p{
  padding:4px;
}
`}</style>
      <main className="max-w-lg mx-auto my-20 ">
        <div className="flex flex-col">
          {/* table header */}
          <div className="flex justify-between">
            <p className="bg-blue-500 border text-white w-1/5 ">
              Add to clipboard
            </p>
            <p className="bg-orange-500 border w-1/4">Chat Id</p>
            <p className="bg-green-500 border w-[55%]">Title</p>
          </div>
          {/* table body */}
          <div className="flex flex-col">
            {/* cell container */}
            {chatData.map((item) => (
              <div className=" flex " key={item.id}>
                <p
                  className="border-blue-500 border  w-1/5 flex justify-center items-center cursor-pointer"
                  onClick={() => {
                    addToClipboard(item.id);
                  }}
                >
                  <BsClipboardPlus />
                </p>
                <p className="border-orange-500 border w-1/4">{item.id}</p>
                <p className="border-green-500 border w-[55%]">{item.title}</p>
              </div>
            ))}
          </div>
        </div>
      </main>
    </div>
  );
}
